### ISSUE TITLE
go get gitlab.com/yzzyx/zerr stuck on v1.0.0

### ISSUE THREAD

**Issue by nikitabuyevich** [yzzyx/zerr#4]
I'm unfamiliar with how to publish a package in `Go` but it seems like when I add the `zerr` package as a dependency in my project, it's only ever finding `v1.0.0` when the latest release is `v1.3.0`. Is that correct?

**Comment by yzzyx** [comment]
it seems the version on gitlab has not been updated properly.
It has been updated now, and both `go get gitlab.com/yzzyx/zerr` and `go get github.com/yzzyx/zerr`  should result in v1.3.0

**Comment by yzzyx** [comment]
correction - as of right now, `github.com/yzzyx/zerr` should be used, or go complains about import paths.
I'll update the readme.

**Comment by yzzyx** [comment]
README updated in PR #5
